# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('linklifetime', ['mobility', 'internet', 'network', 'applications', 'wifi'])
    module.source = [
        'model/linklifetime.cc',
        'model/markovchain-mobility-model.cc',
        'model/discovery-packet-header.cc',
        'model/reply-packet-header.cc',
        'model/myrtable.cc',
        'model/discovery-application.cc',
        'helper/linklifetime-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('linklifetime')
    module_test.source = [
        'test/linklifetime-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'linklifetime'
    headers.source = [
        'model/linklifetime.h',
        'model/markovchain-mobility-model.h',
        'model/discovery-packet-header.h',
        'model/reply-packet-header.h',
        'model/myrtable.h',
        'model/discovery-application.h',
        'helper/linklifetime-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

